/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Tablet.gltf 
Author: NexXer (https://sketchfab.com/nexxer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sog-sorosuub-corp-tablet-7376b978a0994f6fb7bb7511ec421c68
Title: [SoG] Sorosuub Corp. tablet
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Tablet.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.009, -0.005]} rotation={[-0.587, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.tabletshapeSG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.windowSG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Tablet.gltf");
